apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql
  labels:
    app: psql
    tier: air-quality
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
      - name: psql
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PSQL_ROOT_PASS
              name: air-quality-env
        image: gcr.io/sandbox-abg/postgresql_air:v1
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: psql-service
  labels:
    app: psql
spec:
  selector:
    app: psql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432